name: contact
version: 0.0.1
author: Evèssèhou Moïse Dovonou <dovonoumoise@yahoo.fr>
description: Simple application web pour la gestion des contacts
dependencies:
  browser: any
  dartlero:
    git: git://github.com/dzenanr/dartlero.git
